//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebReceiveMessageRealTime.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FB_MessengerRealtime
    {
        public long Id { get; set; }
        public long SenderId { get; set; }
        public long RecipientId { get; set; }
        public Nullable<System.DateTime> TimeSend { get; set; }
        public string Message { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.DateTime> Log_CreatedDate { get; set; }
        public string Log_CreatedBy { get; set; }
        public Nullable<System.DateTime> Log_UpdatedDate { get; set; }
        public string Log_UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] TimeStamp { get; set; }
        public string TimeStampText { get; set; }
    }
}
