//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebReceiveMessageRealTime.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FB_PageInfo
    {
        public long Id { get; set; }
        public long PageId { get; set; }
        public string PageName { get; set; }
        public string Category { get; set; }
        public string AccessToken { get; set; }
        public string LinkToPage { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public long UserId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> Log_CreatedDate { get; set; }
        public string Log_CreatedBy { get; set; }
        public Nullable<System.DateTime> Log_UpdatedDate { get; set; }
        public string Log_UpdatedBy { get; set; }
        public byte[] TimeStamp { get; set; }
        public string TimeStampText { get; set; }
    }
}
