//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebReceiveMessageRealTime
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Ajuma_devEntities : DbContext
    {
        public Ajuma_devEntities()
            : base("name=Ajuma_devEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Supplier> Suppliers { get; set; }
    
        public virtual int sp_GetBillTransfer_Json(string jsonParam, ObjectParameter jsonOutput)
        {
            var jsonParamParameter = jsonParam != null ?
                new ObjectParameter("jsonParam", jsonParam) :
                new ObjectParameter("jsonParam", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetBillTransfer_Json", jsonParamParameter, jsonOutput);
        }
    }
}
