//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebReceiveMessageRealTime
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SOLIDDB_DEVEntities : DbContext
    {
        public SOLIDDB_DEVEntities()
            : base("name=SOLIDDB_DEVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FB_MessengerRealtime> FB_MessengerRealtime { get; set; }
        public virtual DbSet<FBConversationDetail_Image> FBConversationDetail_Image { get; set; }
        public virtual DbSet<FBConversationDetail_ImageBillNotPaidMoment> FBConversationDetail_ImageBillNotPaidMoment { get; set; }
        public virtual DbSet<FB_Log> FB_Log { get; set; }
    
        public virtual ObjectResult<sp_Fb_GetCusBySenderId_Result> sp_Fb_GetCusBySenderId(Nullable<long> senderId)
        {
            var senderIdParameter = senderId.HasValue ?
                new ObjectParameter("SenderId", senderId) :
                new ObjectParameter("SenderId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Fb_GetCusBySenderId_Result>("sp_Fb_GetCusBySenderId", senderIdParameter);
        }
    }
}
