//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebReceiveMessageRealTime
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SOLIDDB_DEVEntities : DbContext
    {
        public SOLIDDB_DEVEntities()
            : base("name=SOLIDDB_DEVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FB_MessengerRealtime> FB_MessengerRealtime { get; set; }
        public virtual DbSet<FBConversationDetail_Image> FBConversationDetail_Image { get; set; }
    
        public virtual ObjectResult<sp_FB_GetListConversationIds_Result> sp_FB_GetListConversationIds(string listCustomerIds)
        {
            var listCustomerIdsParameter = listCustomerIds != null ?
                new ObjectParameter("listCustomerIds", listCustomerIds) :
                new ObjectParameter("listCustomerIds", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_FB_GetListConversationIds_Result>("sp_FB_GetListConversationIds", listCustomerIdsParameter);
        }
    }
}
