//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebReceiveMessageRealTime
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBConversationDetail_ImageBillNotPaidMoment
    {
        public long Id { get; set; }
        public Nullable<long> FBConversationDetail_ImageId { get; set; }
        public Nullable<long> BillId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> Log_CreatedDate { get; set; }
        public string Log_CreatedBy { get; set; }
        public Nullable<System.DateTime> Log_UpdatedDate { get; set; }
        public string Log_UpdatedBy { get; set; }
    
        public virtual FBConversationDetail_Image FBConversationDetail_Image { get; set; }
    }
}
