//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebReceiveMessageRealTime
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBConversationDetail_Image
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FBConversationDetail_Image()
        {
            this.FBConversationDetail_ImageBillNotPaidMoment = new HashSet<FBConversationDetail_ImageBillNotPaidMoment>();
        }
    
        public long Id { get; set; }
        public string ConversationId { get; set; }
        public string CustomerFbName { get; set; }
        public string LinkToChat { get; set; }
        public string ImageText { get; set; }
        public bool IsBankTransfer { get; set; }
        public Nullable<System.DateTime> TimeReceiveFromSource { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> Log_CreatedDate { get; set; }
        public string Log_CreatedBy { get; set; }
        public Nullable<System.DateTime> Log_UpdatedDate { get; set; }
        public string Log_UpdatedBy { get; set; }
        public Nullable<decimal> CusMoneyNotTransferBefore { get; set; }
        public bool IsLikeBankTransfer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FBConversationDetail_ImageBillNotPaidMoment> FBConversationDetail_ImageBillNotPaidMoment { get; set; }
    }
}
