//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebReceiveMessageRealTime
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBConversationDetail_Image
    {
        public long Id { get; set; }
        public string ConversationId { get; set; }
        public string CustomerFbName { get; set; }
        public string LinkToChat { get; set; }
        public string ImageText { get; set; }
        public bool IsBankTransfer { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> Log_CreatedDate { get; set; }
        public string Log_CreatedBy { get; set; }
        public Nullable<System.DateTime> Log_UpdatedDate { get; set; }
        public string Log_UpdatedBy { get; set; }
    }
}
